### ISSUE TITLE
Problema ejercicio 2 capitulo 10 (haskell)

### ISSUE THREAD

**Issue by Guille1990** [Marcombo/computacion-calculo-lambda-programacion-funcional#1]
Ejercicio 2, incrementar recursivo.

El intentar compilar el código se muestra un mensaje de warning
```
  increment.hs:3:1: warning: [-Woverlapping-patterns]
    Pattern match is redundant
    In an equation for ‘increment’: increment 10 = ...
  |
3 | increment 10 = 10
  | ^^^^^^^^^^^^^^^^^
````

La compilación se realiza pero al ejecutar el código no hay ningún output y el programa se mantiene en ejecución.

**Comment by camilochs** [comment]
Hola Guillermo,

Al parecer hay un problema con la versión de Haskell.

Hay que cambiar el orden del _pattern matching_:

```
increment :: Int -> Int
increment 10 = 10
increment n = increment (n + 1)
main = print $ increment 0
-- 10
```

Lo probé en: [https://replit.com/languages/haskell](https://replit.com/languages/haskell) y funcionó.

**Comment by Guille1990** [comment]
Gracias @camilochs, me funciona correctamente el ejemplo con ese cambio
